### ISSUE TITLE
建议 pnpm dev:xxx 时可以自动生成 manifest.json

### ISSUE THREAD

**Issue by codercup** [uni-helper/vite-plugin-uni-manifest#18]
### 对问题的清晰和简明的描述

建议 pnpm dev:xxx 时可以自动生成 manifest.json, 这样就可以把 manifest.json 放入 .gitignore

### 推荐的解决方案

提供一个钩子，可以自动生成 manifest.json, 或者用户可以配置默认生成。

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
暂无计划，你可以通过  postinstall script 生成一个空 manifest.json
