### ISSUE TITLE
建议 build:xxx的时候可以自动重新生成manifest.json

### ISSUE THREAD

**Issue by jocstech** [uni-helper/vite-plugin-uni-manifest#22]
### 对问题的清晰和简明的描述

建议 build:xxx的时候可以自动重新生成manifest.json 这样方便在本地用脚本做自动版本号提升，可以直接gitignore  manifest.json 这个文件，请考虑一下。

### 推荐的解决方案

建议 build:xxx的时候可以自动重新生成manifest.json 这样方便在本地用脚本做自动版本号提升，可以直接gitignore  manifest.json 这个文件，请考虑一下。

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
#18

**Comment by KeJunMao** [comment]
不考虑实现的原因是 uniapp 的 cli 在启动前依赖这个文件，而 uniapp 的cli 没有相关的钩子可以用
