### ISSUE TITLE
配置payment支付方式错误，模块打包不进去

### ISSUE THREAD

**Issue by CherishMvp** [uni-helper/vite-plugin-uni-manifest#45]
### 描述问题

 按照manifest.json原生配置的配置项，一摸一样的的放在manifest.config里。payment打包不进去。push模块可以，payment有问题

### 复现

 按照manifest.json原生配置的配置项，一摸一样的的放在manifest.config里。payment打包不进去。push模块可以，payment有问题

### 系统信息

 按照manifest.json原生配置的配置项，一摸一样的的放在manifest.config里。payment打包不进去。push模块可以，payment有问题

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by CherishMvp** [comment]
不好意思，今天仔细排查发现是Payment大小写区别

**Comment by wowoName** [comment]
Payment 下的微信支付信息为什么不能打包进去，跟大小写有关系吗

**Comment by wowoName** [comment]
@CherishMvp
